### ISSUE TITLE
Cannot run "experiments/encoder_ppo_sp_experiments_lstm.py"

### ISSUE THREAD

**Issue by hogebein** [yanxue7/E3T-Overcooked#1]
When I try to run "experiments/encoder_ppo_sp_experiments_lstm.py" by following the readme, I get the error message:

Traceback (most recent call last):
  File "experiments/encoder_ppo_sp_experiments_lstm.py", line 16, in <module>
    from human_aware_rl.imitation.behavioural_cloning import get_bc_agent_from_saved,get_bc_agent_from_saved_added
ImportError: cannot import name 'get_bc_agent_from_saved_added' from 'human_aware_rl.imitation.behavioural_cloning' 

I have checked what is written in the original (NeuIPS 2019) "human_aware_rl.imitation.behavioural_cloning", but there was no method named "get_bc_agent_from_saved_added".

I guess this is a modification of yours, but I think you haven't provided the latest version of 'human_aware_rl.imitation.behavioural_cloning' .
Can I ask you have a check on this one?

**Comment by yanxue7** [comment]
Thanks for pointing out this problem.
indeed, we have implemented a new function "get_bc_agent_from_saved_added" in "human_aware_rl.imitation.behavioural_cloning". And we have uploaded this human_aware_rl.imitation.behavioural_cloning.py file.
